// desktopexporter/internal/app/components/detail-view/events-panel.tsx
import React from "react";
import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Heading,
  List,
  TabPanel,
  Text,
} from "@chakra-ui/react";

import { EventData } from "../../types/api-types";
import { SpanField } from "./span-field";
import { parseAttributeType } from "../../utils/parse-type";
import { PreciseTimestamp } from "../../types/precise-timestamp";
import { formatDuration } from "../../utils/duration";

type EventItemProps = {
  event: EventData;
  spanStartTime: PreciseTimestamp;
};

function EventItem(props: EventItemProps) {
  let { event, spanStartTime } = props;
  let timeSinceSpanStart = formatDuration(event.timestamp.nanoseconds - spanStartTime.nanoseconds);

  let eventAttributes = Object.entries(event.attributes).map(([key, value]) => (
    <li key={key + value?.toString()}>
      <SpanField
        fieldName={key}
        fieldValue={value.toString()}
        fieldType={parseAttributeType(value)}
      />
    </li>
  ));

  return (
    <AccordionItem>
      <AccordionButton>
        <Box
          flex="1"
          textAlign="left"
        >
          <Heading size="sm">{event.name}</Heading>
          <Text fontSize="xs">{timeSinceSpanStart} since span start</Text>
        </Box>
        <AccordionIcon />
      </AccordionButton>
      <AccordionPanel>
        <SpanField
          fieldName="timestamp"
          fieldValue={event.timestamp.toString()}
          fieldType="timestamp"
        />
        <List>{eventAttributes}</List>
        <SpanField
          fieldName="dropped attributes count"
          fieldValue={event.droppedAttributesCount.toString()}
          fieldType="uint32"
          hidden={!event.droppedAttributesCount}
        />
      </AccordionPanel>
    </AccordionItem>
  );
}

type EventsPanelProps = {
  events: EventData[] | undefined;
  spanStartTime: PreciseTimestamp;
};

export function EventsPanel(props: EventsPanelProps) {
  let { events, spanStartTime } = props;
  if (!events) {
    return null;
  }

  let eventItemList = events.map((event) => (
    <li key={event.name + event.timestamp}>
      <EventItem
        event={event}
        spanStartTime={spanStartTime}
      />
    </li>
  ));

  return (
    <TabPanel paddingX="0px">
      <Accordion allowMultiple>
        <List>{eventItemList}</List>
      </Accordion>
    </TabPanel>
  );
}

// desktopexporter/internal/frontend/src/components/traces/Detail/EventsPanel.svelte
<script lang="ts">
  import type { EventData } from '@/types/api-types'
  import FieldGroup from '@/components/shared/FieldGroup.svelte'
  import SpanField from './SpanField.svelte'
  import { formatDuration, formatTimestamp } from '@/utils/time'
  import { getTimeContext } from '@/contexts/time-context.svelte'

  type Props = {
    events: EventData[]
    spanStartTime: bigint
  }

  let { events, spanStartTime }: Props = $props()

  let timeContext = getTimeContext()

  function eventFieldCount(event: EventData): number {
    let n = 1
    n += event.attributes.length
    if (event.droppedAttributesCount > 0) n++
    return n
  }
</script>

{#each events as event, index (index)}
  <FieldGroup
    label={event.name}
    badge={`+${formatDuration(event.timestamp - spanStartTime)}`}
    count={eventFieldCount(event)}
    open={index === 0}
  >
    <table class="detail-fields w-full" aria-label="Event {event.name}">
      <tbody>
        <SpanField
          fieldName="timestamp"
          fieldValue={formatTimestamp(
            event.timestamp,
            timeContext.tz,
            'nanoseconds'
          )}
          fieldType="timestamp"
        />
        {#each event.attributes as attr (attr.key)}
          <SpanField
            fieldName={attr.key}
            fieldValue={attr.value}
            fieldType={attr.type}
          />
        {/each}
        {#if event.droppedAttributesCount > 0}
          <SpanField
            fieldName="dropped attributes count"
            fieldValue={event.droppedAttributesCount.toString()}
            fieldType="uint32"
          />
        {/if}
      </tbody>
    </table>
  </FieldGroup>
{/each}
