// desktopexporter/internal/frontend/src/components/TraceDetails/FieldsPanel.svelte
<script lang="ts">
  import type { SpanData } from '@/types/api-types';
  import SpanField from './SpanField.svelte';
  import { formatDuration } from '@/utils/duration';

  type Props = {
    span: SpanData | undefined;
  };

  let { span }: Props = $props();

  let isRoot = $derived(span?.parentSpanID.length === 0);
  let spanDataOpen = $state(true);
  let resourceDataOpen = $state(true);
  let scopeDataOpen = $state(true);
  let durationLabel = $derived(
    span
      ? formatDuration(span.endTime.nanoseconds - span.startTime.nanoseconds)
      : ''
  );

  let spanAttributes = $derived(
    span
      ? Object.entries(span.attributes).map(([key, value]) => ({
          key,
          name: key,
          value: value.toString(),
          type: 'type',
        }))
      : []
  );

  let resourceAttributes = $derived(
    span
      ? Object.entries(span.resource.attributes).map(([key, value]) => ({
          key,
          name: key,
          value: value.toString(),
          type: 'type',
        }))
      : []
  );

  let scopeAttributes = $derived(
    span
      ? Object.entries(span.scope.attributes).map(([key, value]) => ({
          key,
          name: key,
          value: value.toString(),
          type: 'type',
        }))
      : []
  );
</script>

{#if span}
  <div class="space-y-2">
    <!-- Span Data -->
    <div class="data-table-section">
      <button
        type="button"
        class="data-table-header"
        onclick={() => (spanDataOpen = !spanDataOpen)}
      >
        <div class="section-header">
          <svg
            class="w-4 h-4 transition-transform {spanDataOpen
              ? 'rotate-180'
              : ''}"
            viewBox="0 0 24 24"
          >
            <path d="M18 9s-4.419 6-6 6s-6-6-6-6" />
          </svg>
          <span>Span Data</span>
          {#if isRoot}
            <span class="badge badge-secondary badge-outline badge-sm ml-2"
              >root</span
            >
          {/if}
        </div>
      </button>
      {#if spanDataOpen}
        <div class="data-table">
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="name"
                fieldValue={span.name}
                fieldType="string"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="kind"
                fieldValue={span.kind}
                fieldType="string"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="start time"
                fieldValue={span.startTime.toString()}
                fieldType="timestamp"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="end time"
                fieldValue={span.endTime.toString()}
                fieldType="timestamp"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="duration"
                fieldValue={durationLabel}
                fieldType="string"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="status code"
                fieldValue={span.statusCode}
                fieldType="string"
              />
            </div>
          </div>
          {#if span.statusCode !== 'Unset' && span.statusCode !== 'Ok'}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="status message"
                  fieldValue={span.statusMessage}
                  fieldType="string"
                />
              </div>
            </div>
          {/if}
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="trace id"
                fieldValue={span.traceID}
                fieldType="string"
              />
            </div>
          </div>
          {#if !isRoot}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="parent span id"
                  fieldValue={span.parentSpanID}
                  fieldType="string"
                />
              </div>
            </div>
          {/if}
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="span id"
                fieldValue={span.spanID}
                fieldType="string"
              />
            </div>
          </div>
          {#each spanAttributes as attr}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName={attr.name}
                  fieldValue={attr.value}
                  fieldType={attr.type}
                />
              </div>
            </div>
          {/each}
          {#if span.droppedAttributesCount > 0}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="dropped attributes count"
                  fieldValue={span.droppedAttributesCount.toString()}
                  fieldType="uint32"
                />
              </div>
            </div>
          {/if}
          {#if span.droppedEventsCount > 0}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="dropped events count"
                  fieldValue={span.droppedEventsCount.toString()}
                  fieldType="uint32"
                />
              </div>
            </div>
          {/if}
          {#if span.droppedLinksCount > 0}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="dropped links count"
                  fieldValue={span.droppedLinksCount.toString()}
                  fieldType="uint32"
                />
              </div>
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <!-- Resource Data -->
    <div class="data-table-section">
      <button
        type="button"
        class="data-table-header"
        onclick={() => (resourceDataOpen = !resourceDataOpen)}
      >
        <div class="section-header">
          <svg
            class="w-4 h-4 transition-transform {resourceDataOpen
              ? 'rotate-180'
              : ''}"
            viewBox="0 0 24 24"
          >
            <path d="M18 9s-4.419 6-6 6s-6-6-6-6" />
          </svg>
          <span>Resource Data</span>
        </div>
      </button>
      {#if resourceDataOpen}
        <div class="data-table">
          {#each resourceAttributes as attr}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName={attr.name}
                  fieldValue={attr.value}
                  fieldType={attr.type}
                />
              </div>
            </div>
          {/each}
          {#if span.resource.droppedAttributesCount > 0}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="dropped attributes count"
                  fieldValue={span.resource.droppedAttributesCount.toString()}
                  fieldType="uint32"
                />
              </div>
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <!-- Scope Data -->
    <div class="data-table-section">
      <button
        type="button"
        class="data-table-header"
        onclick={() => (scopeDataOpen = !scopeDataOpen)}
      >
        <div class="section-header">
          <svg
            class="w-4 h-4 transition-transform {scopeDataOpen
              ? 'rotate-180'
              : ''}"
            viewBox="0 0 24 24"
          >
            <path d="M18 9s-4.419 6-6 6s-6-6-6-6" />
          </svg>
          <span>Scope Data</span>
        </div>
      </button>
      {#if scopeDataOpen}
        <div class="data-table">
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="scope name"
                fieldValue={span.scope.name}
                fieldType="string"
              />
            </div>
          </div>
          <div class="data-table-row">
            <div class="data-table-cell">
              <SpanField
                fieldName="scope version"
                fieldValue={span.scope.version}
                fieldType="string"
              />
            </div>
          </div>
          {#each scopeAttributes as attr}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName={attr.name}
                  fieldValue={attr.value}
                  fieldType={attr.type}
                />
              </div>
            </div>
          {/each}
          {#if span.scope.droppedAttributesCount > 0}
            <div class="data-table-row">
              <div class="data-table-cell">
                <SpanField
                  fieldName="dropped attributes count"
                  fieldValue={span.scope.droppedAttributesCount.toString()}
                  fieldType="uint32"
                />
              </div>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>
{:else}
  <p class="text-base-content/60">Nothing here yet.</p>
{/if}

<style>
  .section-header {
    @apply text-sm font-semibold text-base-content py-2 px-4 flex items-center gap-2;
  }

  .data-table-section {
    @apply border border-base-300 rounded-lg overflow-hidden;
  }

  .data-table-header {
    @apply w-full text-left cursor-pointer hover:bg-base-200 transition-colors border-none bg-transparent;
  }

  .data-table {
    display: table;
    width: 100%;
    border-collapse: collapse;
  }

  .data-table-row {
    display: table-row;
    border-top: 1px solid hsl(var(--b3));
  }

  .data-table-row:first-child {
    border-top: none;
  }

  .data-table-cell {
    display: table-cell;
    width: 100%;
    padding: 0;
  }
</style>

// desktop-exporter/app/components/detail-view/fields-panel.tsx
import React from "react";
import {
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  TabPanel,
  Box,
  AccordionIcon,
  List,
  Heading,
  Tag,
} from "@chakra-ui/react";

import { SpanData } from "../../types/api-types";
import { SpanField } from "./span-field";
import { getDurationNs, getDurationString } from "../../utils/duration";

type FieldsPanelProps = {
  span: SpanData | undefined;
};

export function FieldsPanel(props: FieldsPanelProps) {
  let { span } = props;
  if (!span) {
    return (
      <TabPanel>
        <p>Nothing here yet.</p>
      </TabPanel>
    );
  }

  // Root span: label with a little tag
  let isRoot = span.parentSpanID.length ? false : true;
  let rootTag = isRoot ? (
    <Tag
      marginStart={2}
      colorScheme="cyan"
      variant="subtle"
    >
      root
    </Tag>
  ) : null;

  // Duration: label in appropriate human-readable time unit (s, ms, μs, ns)

  let durationString = getDurationString(
    getDurationNs(span.startTime, span.endTime),
  );

  // Attributes:
  let spanAttributes = Object.entries(span.attributes).map(([key, value]) => (
    <li key={key}>
      <SpanField
        fieldName={key}
        fieldValue={value}
      />
    </li>
  ));

  let resourceAttributes = Object.entries(span.resource.attributes).map(
    ([key, value]) => (
      <li key={key}>
        <SpanField
          fieldName={key}
          fieldValue={value}
        />
      </li>
    ),
  );

  let scopeAttributes = Object.entries(span.scope.attributes).map(
    ([key, value]) => (
      <li key={key}>
        <SpanField
          fieldName={key}
          fieldValue={value}
        />
      </li>
    ),
  );

  return (
    <TabPanel paddingX="0px">
      <Accordion
        defaultIndex={[0]}
        allowMultiple
      >
        <AccordionItem>
          <AccordionButton>
            <Box
              flex="1"
              textAlign="left"
            >
              <Heading
                lineHeight="revert"
                size="sm"
              >
                Span Data{rootTag}
              </Heading>
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel>
            <SpanField
              fieldName="name"
              fieldValue={span.name}
            />
            <SpanField
              fieldName="kind"
              fieldValue={span.kind}
            />
            <SpanField
              fieldName="start time"
              fieldValue={span.startTime}
            />
            <SpanField
              fieldName="end time"
              fieldValue={span.endTime}
            />
            <SpanField
              fieldName="duration"
              fieldValue={durationString}
            />
            <SpanField
              fieldName="status code"
              fieldValue={span.statusCode}
            />
            <SpanField
              fieldName="status message"
              fieldValue={span.statusMessage}
              hidden={span.statusCode === "Unset" || span.statusCode === "Ok"}
            />
            <SpanField
              fieldName="trace id"
              fieldValue={span.traceID}
            />
            <SpanField
              fieldName="parent span id"
              fieldValue={span.parentSpanID}
              hidden={isRoot}
            />
            <SpanField
              fieldName="span id"
              fieldValue={span.spanID}
            />
            <List>{spanAttributes}</List>
            <SpanField
              fieldName="dropped attributes count"
              fieldValue={span.droppedAttributesCount}
              hidden={span.droppedAttributesCount === 0}
            />
            <SpanField
              fieldName="dropped events count"
              fieldValue={span.droppedEventsCount}
              hidden={span.droppedEventsCount === 0}
            />
            <SpanField
              fieldName="dropped links count"
              fieldValue={span.droppedLinksCount}
              hidden={span.droppedLinksCount === 0}
            />
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box
              flex="1"
              textAlign="left"
            >
              <Heading size="sm">Resource Data</Heading>
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel>
            <List>{resourceAttributes}</List>
            <SpanField
              fieldName="dropped attributes count"
              fieldValue={span.resource.droppedAttributesCount}
              hidden={span.resource.droppedAttributesCount === 0}
            />
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box
              flex="1"
              textAlign="left"
            >
              <Heading size="sm">Scope Data</Heading>
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel>
            <SpanField
              fieldName="scope name"
              fieldValue={span.scope.name}
            />
            <SpanField
              fieldName="scope version"
              fieldValue={span.scope.version}
            />
            <List>{scopeAttributes}</List>
            <SpanField
              fieldName="dropped attributes count"
              fieldValue={span.scope.droppedAttributesCount}
              hidden={span.scope.droppedAttributesCount === 0}
            />
          </AccordionPanel>
        </AccordionItem>
      </Accordion>
    </TabPanel>
  );
}
